"use strict";
let firstName = "Jasmin";
let lastName = "Korat";
let myAge = 21;
let fullName = firstName + " " + lastName + " " + myAge;
console.log("FullName---------->", fullName);
console.log("Type Of Fullname-->", typeof fullName);
console.log("length------------>", fullName.length);
console.log("UPPERCASE--------->", fullName.toUpperCase());
console.log("lowercase--------->", fullName.toLowerCase());
